[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
swap = "F8Ve3vB9yZvZNUe7Zo35Gycbzc7wQPRazEj2KHkF4c9f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ormon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/swap.ts"
